theme = "nord-dark"
icons = "awesome"


[[block]]
block = "disk_space"
alias = " HOME"
format = "{icon}{alias} {used}/{available}"
path = "/home"
unit = "GB"


[[block]]
block = "disk_space"
alias = " ROOT"
format = "{icon}{alias} {used}/{available}"
path = "/"
unit = "GB"


[[block]]
block = "net"
device = "wlo1"
format = "{ssid} {ip} {speed_down} {speed_up}"
interval = 5


[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 1


[[block]]
block = "sound"
format = "{volume}"
max_vol = 100
show_volume_when_muted = true


[[block]]
block = "battery"
interval = 10
device = "/sys/class/power_supply/BAT1"
driver = "sysfs"
format = "{percentage}"
warning = 15


[[block]]
block = "time"
interval = 60
format = "%Y/%b/%d  %H:%M %P"

